apiVersion: v1
kind: ReplicationController
metadata:
        name: dev
spec:
        replicas: 3
        selector:
                team: christ
        template:
                metadata:
                        name: dev
                        labels:
                                team: christ
                spec:
                        containers:
                        - name: dev
                          image: nginx:1.7.1
                          ports:
                          - containerPort: 80
